local ok, indent = pcall(require, "indent_blankline")
if not ok then
  return
end

indent.setup {
  enabled = true,
  disable_with_nolist = false,
  filetype = {},
  filetype_exclude = {
    "help",
    "terminal",
    "dashboard",
    "packer",
    "startify",
    "neogitstatus",
    "NvimTree",
    "Trouble",
  },
  buftype_exclude = { "terminal", "nofile" },
  bufname_exclude = {},
  char = "│",
  char_blankline = "",
  char_list = {},
  char_list_blankline = {},
  char_highlight_list = {},
  space_char_blankline = " ",
  space_char_highlight_list = {},
  space_char_blankline_highlight_list = {},
  use_treesitter = true,
  indent_level = 10,
  max_indent_increase = 1,
  show_first_indent_level = false,
  show_trailing_blankline_indent = false,
  show_end_of_line = false,
  show_foldtext = true,
  strict_tabs = false,
  show_current_context = true,
  show_current_context_start = false,
  show_current_context_start_on_current_line = true,
  context_char = "│",
  context_char_blankline = "",
  context_char_list = {},
  context_char_list_blankline = {},
  context_highlight_list = {},
  context_patterns = {
    "class",
    "^func",
    "method",
    "^if",
    "while",
    "for",
    "with",
    "try",
    "except",
    "arguments",
    "argument_list",
    "object",
    "dictionary",
    "element",
    "table",
    "tuple",
  },
  context_pattern_highlight = {},
  viewport_buffer = 10,
  disable_warning_message = false,
  debug = false,
}
